// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ecf_reg_test_stat
double ecf_reg_test_stat(const arma::vec& e1, const arma::vec& e01, const arma::vec& e2, const arma::vec& e02);
RcppExport SEXP _TCDT_ecf_reg_test_stat(SEXP e1SEXP, SEXP e01SEXP, SEXP e2SEXP, SEXP e02SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type e1(e1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type e01(e01SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type e2(e2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type e02(e02SEXP);
    rcpp_result_gen = Rcpp::wrap(ecf_reg_test_stat(e1, e01, e2, e02));
    return rcpp_result_gen;
END_RCPP
}
// teststatg
double teststatg(int n1, int n2, const arma::mat& kY11, const arma::mat& kY22, const arma::mat& kY12, const arma::mat& G1_11, const arma::mat& G1_12, const arma::mat& G2_22, const arma::mat& G2_21, const arma::vec& S1_1, const arma::vec& S1_2, const arma::vec& S2_1, const arma::vec& S2_2);
RcppExport SEXP _TCDT_teststatg(SEXP n1SEXP, SEXP n2SEXP, SEXP kY11SEXP, SEXP kY22SEXP, SEXP kY12SEXP, SEXP G1_11SEXP, SEXP G1_12SEXP, SEXP G2_22SEXP, SEXP G2_21SEXP, SEXP S1_1SEXP, SEXP S1_2SEXP, SEXP S2_1SEXP, SEXP S2_2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type kY11(kY11SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type kY22(kY22SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type kY12(kY12SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type G1_11(G1_11SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type G1_12(G1_12SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type G2_22(G2_22SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type G2_21(G2_21SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type S1_1(S1_1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type S1_2(S1_2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type S2_1(S2_1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type S2_2(S2_2SEXP);
    rcpp_result_gen = Rcpp::wrap(teststatg(n1, n2, kY11, kY22, kY12, G1_11, G1_12, G2_22, G2_21, S1_1, S1_2, S2_1, S2_2));
    return rcpp_result_gen;
END_RCPP
}
// teststatl
double teststatl(int n1, int n2, const arma::mat& kY11, const arma::mat& kY22, const arma::mat& kY12, const arma::vec& G1X, const arma::vec& G2X, double S1_1, double S1_2, double S2_1, double S2_2);
RcppExport SEXP _TCDT_teststatl(SEXP n1SEXP, SEXP n2SEXP, SEXP kY11SEXP, SEXP kY22SEXP, SEXP kY12SEXP, SEXP G1XSEXP, SEXP G2XSEXP, SEXP S1_1SEXP, SEXP S1_2SEXP, SEXP S2_1SEXP, SEXP S2_2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type kY11(kY11SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type kY22(kY22SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type kY12(kY12SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type G1X(G1XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type G2X(G2XSEXP);
    Rcpp::traits::input_parameter< double >::type S1_1(S1_1SEXP);
    Rcpp::traits::input_parameter< double >::type S1_2(S1_2SEXP);
    Rcpp::traits::input_parameter< double >::type S2_1(S2_1SEXP);
    Rcpp::traits::input_parameter< double >::type S2_2(S2_2SEXP);
    rcpp_result_gen = Rcpp::wrap(teststatl(n1, n2, kY11, kY22, kY12, G1X, G2X, S1_1, S1_2, S2_1, S2_2));
    return rcpp_result_gen;
END_RCPP
}
// cv_objective
double cv_objective(const arma::vec& C, const arma::mat& X, const arma::mat& kY, const arma::vec& local_weights, double kappa, double nu, int kern_type, double lower_C, double tiny_num);
RcppExport SEXP _TCDT_cv_objective(SEXP CSEXP, SEXP XSEXP, SEXP kYSEXP, SEXP local_weightsSEXP, SEXP kappaSEXP, SEXP nuSEXP, SEXP kern_typeSEXP, SEXP lower_CSEXP, SEXP tiny_numSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type kY(kYSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type local_weights(local_weightsSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< int >::type kern_type(kern_typeSEXP);
    Rcpp::traits::input_parameter< double >::type lower_C(lower_CSEXP);
    Rcpp::traits::input_parameter< double >::type tiny_num(tiny_numSEXP);
    rcpp_result_gen = Rcpp::wrap(cv_objective(C, X, kY, local_weights, kappa, nu, kern_type, lower_C, tiny_num));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TCDT_ecf_reg_test_stat", (DL_FUNC) &_TCDT_ecf_reg_test_stat, 4},
    {"_TCDT_teststatg", (DL_FUNC) &_TCDT_teststatg, 13},
    {"_TCDT_teststatl", (DL_FUNC) &_TCDT_teststatl, 11},
    {"_TCDT_cv_objective", (DL_FUNC) &_TCDT_cv_objective, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_TCDT(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
