# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ecf_reg_test_stat <- function(e1, e01, e2, e02) {
    .Call(`_TCDT_ecf_reg_test_stat`, e1, e01, e2, e02)
}

teststatg <- function(n1, n2, kY11, kY22, kY12, G1_11, G1_12, G2_22, G2_21, S1_1, S1_2, S2_1, S2_2) {
    .Call(`_TCDT_teststatg`, n1, n2, kY11, kY22, kY12, G1_11, G1_12, G2_22, G2_21, S1_1, S1_2, S2_1, S2_2)
}

teststatl <- function(n1, n2, kY11, kY22, kY12, G1X, G2X, S1_1, S1_2, S2_1, S2_2) {
    .Call(`_TCDT_teststatl`, n1, n2, kY11, kY22, kY12, G1X, G2X, S1_1, S1_2, S2_1, S2_2)
}

#' @title CV Objective Function (C++ Backend)
#' @description Calculates the (potentially locally weighted) leave-one-out
#' cross-validation loss.
#' @param C A numeric vector of scaling factors for the bandwidth.
#' @param X A numeric matrix of predictors.
#' @param kY The precomputed RKHS kernel matrix for the response.
#' @param local_weights A numeric vector of pre-computed weights for each
#'   observation, used for locally weighted CV. For standard CV, this should
#'   be a vector of ones.
#' @param kappa The exponent for the sample size in the bandwidth formula.
#' @param nu The order of the smoothing kernel.
#' @param kern_type An integer mapping to the kernel function.
#' @param lower_C The lower bound for C values.
#' @param tiny_num A small number to prevent division by zero.
#' @keywords internal
cv_objective <- function(C, X, kY, local_weights, kappa, nu, kern_type, lower_C, tiny_num = 1e-12) {
    .Call(`_TCDT_cv_objective`, C, X, kY, local_weights, kappa, nu, kern_type, lower_C, tiny_num)
}

